### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by MacroPower** [fhemberger/chrome-prometheus-formatter#10]
I've modified this plugin to have a dark theme, based on Atom One Dark.

![image](https://user-images.githubusercontent.com/5648814/84676857-f6459100-aefb-11ea-9770-0908d700b919.png)

Is there any interest in having this as a new "default", since there's currently no way to switch between themes? If so, I can submit a PR.

**Comment by fhemberger** [comment]
Hi, that looks cool! The easiest way would be to extend [content.js](https://github.com/fhemberger/prometheus-formatter/blob/master/extension/js/content.js#L62) and add some additional CSS:

```css
/* Those are the regular colors, you just have to replace
   them with the ones from your dark version */
@media (prefers-color-scheme:dark) {
  body         { background-color: #fff }
  .metric      { color: #000 }
  .value       { color: #ff20ed }
  .label-key   { color: blue }
  .label-value { color: green }
  .comment     { color: #6a737d }
}
```

If your browser/OS is set to dark mode, the alternative colors are used.
